[versions]
agp = "8.13.0"
kotlin = "2.2.21"

rules = "1.7.0"
runner = "1.7.0"

[libraries]
androidx-rules = { module = "androidx.test:rules", version.ref = "rules" }
androidx-runner = { module = "androidx.test:runner", version.ref = "runner" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
